namespace GreenshotOfficePlugin.OfficeInterop.Powerpoint
{
    public enum PPSlideLayout : int {
        ppLayoutMixed = -2,
        ppLayoutTitle = 1,
        ppLayoutText = 2,
        ppLayoutTwoColumnText = 3,
        ppLayoutTable = 4,
        ppLayoutTextAndChart = 5,
        ppLayoutChartAndText = 6,
        ppLayoutOrgchart = 7,
        ppLayoutChart = 8,
        ppLayoutTextAndClipart = 9,
        ppLayoutClipartAndText = 10,
        ppLayoutTitleOnly = 11,
        ppLayoutBlank = 12,
        ppLayoutTextAndObject = 13,
        ppLayoutObjectAndText = 14,
        ppLayoutLargeObject = 15,
        ppLayoutObject = 16,
        ppLayoutTextAndMediaClip = 17,
        ppLayoutMediaClipAndText = 18,
        ppLayoutObjectOverText = 19,
        ppLayoutTextOverObject = 20,
        ppLayoutTextAndTwoObjects = 21,
        ppLayoutTwoObjectsAndText = 22,
        ppLayoutTwoObjectsOverText = 23,
        ppLayoutFourObjects = 24,
        ppLayoutVerticalText = 25,
        ppLayoutClipArtAndVerticalText = 26,
        ppLayoutVerticalTitleAndText = 27,
        ppLayoutVerticalTitleAndTextOverChart = 28,
        ppLayoutTwoObjects = 29,
        ppLayoutObjectAndTwoObjects = 30,
        ppLayoutTwoObjectsAndObject = 31,
        ppLayoutCustom = 32,
        ppLayoutSectionHeader = 33,
        ppLayoutComparison = 34,
        ppLayoutContentWithCaption = 35,
        ppLayoutPictureWithCaption = 36
    }
}