<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
  <ItemGroup>
    <None Include="Languages\greenshot*.ini">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Greenshot.Base\Greenshot.Base.csproj" />
    <PackageReference Include="Dapplo.Windows.Com" Version="3.13.5" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Update="Microsoft.CodeAnalysis.BannedApiAnalyzers" Version="5.6.0" />
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23" />
  </ItemGroup>

</Project>
