//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.269
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.269.
// 
#pragma warning disable 1591

namespace GreenshotConfluencePlugin.confluence {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="confluenceservice-v1SoapBinding", Namespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(Vector))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePermission))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteNodeStatus))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteUserInformation))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePageUpdateOptions))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePageHistory))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteContentSummaries))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteContentSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSpaceGroup))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteLabel))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteContentPermissionSet))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteContentPermission))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteClusterInformation))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteUser))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AbstractRemotePageSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteServerInfo))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSpaceSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSearchResult))]
    public partial class ConfluenceSoapServiceService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback searchOperationCompleted;
        
        private System.Threading.SendOrPostCallback search1OperationCompleted;
        
        private System.Threading.SendOrPostCallback getSpaceOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCommentOperationCompleted;
        
        private System.Threading.SendOrPostCallback getChildrenOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPageOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPage1OperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAttachmentOperationCompleted;
        
        private System.Threading.SendOrPostCallback addAttachment1OperationCompleted;
        
        private System.Threading.SendOrPostCallback getSpacesOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPagesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ConfluenceSoapServiceService() {
            this.Url = "http://confluence/rpc/soap-axis/confluenceservice-v1";
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event searchCompletedEventHandler searchCompleted;
        
        /// <remarks/>
        public event search1CompletedEventHandler search1Completed;
        
        /// <remarks/>
        public event getSpaceCompletedEventHandler getSpaceCompleted;
        
        /// <remarks/>
        public event getCommentCompletedEventHandler getCommentCompleted;
        
        /// <remarks/>
        public event getChildrenCompletedEventHandler getChildrenCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event getPageCompletedEventHandler getPageCompleted;
        
        /// <remarks/>
        public event getPage1CompletedEventHandler getPage1Completed;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        public event addAttachmentCompletedEventHandler addAttachmentCompleted;
        
        /// <remarks/>
        public event addAttachment1CompletedEventHandler addAttachment1Completed;
        
        /// <remarks/>
        public event getSpacesCompletedEventHandler getSpacesCompleted;
        
        /// <remarks/>
        public event getPagesCompletedEventHandler getPagesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("searchReturn")]
        public RemoteSearchResult[] search(string in0, string in1, int in2) {
            object[] results = this.Invoke("search", new object[] {
                        in0,
                        in1,
                        in2});
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public void searchAsync(string in0, string in1, int in2) {
            this.searchAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void searchAsync(string in0, string in1, int in2, object userState) {
            if ((this.searchOperationCompleted == null)) {
                this.searchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsearchOperationCompleted);
            }
            this.InvokeAsync("search", new object[] {
                        in0,
                        in1,
                        in2}, this.searchOperationCompleted, userState);
        }
        
        private void OnsearchOperationCompleted(object arg) {
            if ((this.searchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.searchCompleted(this, new searchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="search1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("searchReturn")]
        public RemoteSearchResult[] search(string in0, string in1, Map in2, int in3) {
            object[] results = this.Invoke("search1", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((RemoteSearchResult[])(results[0]));
        }
        
        /// <remarks/>
        public void search1Async(string in0, string in1, Map in2, int in3) {
            this.search1Async(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void search1Async(string in0, string in1, Map in2, int in3, object userState) {
            if ((this.search1OperationCompleted == null)) {
                this.search1OperationCompleted = new System.Threading.SendOrPostCallback(this.Onsearch1OperationCompleted);
            }
            this.InvokeAsync("search1", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.search1OperationCompleted, userState);
        }
        
        private void Onsearch1OperationCompleted(object arg) {
            if ((this.search1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.search1Completed(this, new search1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSpaceReturn")]
        public RemoteSpace getSpace(string in0, string in1) {
            object[] results = this.Invoke("getSpace", new object[] {
                        in0,
                        in1});
            return ((RemoteSpace)(results[0]));
        }
        
        /// <remarks/>
        public void getSpaceAsync(string in0, string in1) {
            this.getSpaceAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getSpaceAsync(string in0, string in1, object userState) {
            if ((this.getSpaceOperationCompleted == null)) {
                this.getSpaceOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSpaceOperationCompleted);
            }
            this.InvokeAsync("getSpace", new object[] {
                        in0,
                        in1}, this.getSpaceOperationCompleted, userState);
        }
        
        private void OngetSpaceOperationCompleted(object arg) {
            if ((this.getSpaceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSpaceCompleted(this, new getSpaceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getCommentReturn")]
        public RemoteComment getComment(string in0, long in1) {
            object[] results = this.Invoke("getComment", new object[] {
                        in0,
                        in1});
            return ((RemoteComment)(results[0]));
        }
        
        /// <remarks/>
        public void getCommentAsync(string in0, long in1) {
            this.getCommentAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getCommentAsync(string in0, long in1, object userState) {
            if ((this.getCommentOperationCompleted == null)) {
                this.getCommentOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCommentOperationCompleted);
            }
            this.InvokeAsync("getComment", new object[] {
                        in0,
                        in1}, this.getCommentOperationCompleted, userState);
        }
        
        private void OngetCommentOperationCompleted(object arg) {
            if ((this.getCommentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCommentCompleted(this, new getCommentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getChildrenReturn")]
        public RemotePageSummary[] getChildren(string in0, long in1) {
            object[] results = this.Invoke("getChildren", new object[] {
                        in0,
                        in1});
            return ((RemotePageSummary[])(results[0]));
        }
        
        /// <remarks/>
        public void getChildrenAsync(string in0, long in1) {
            this.getChildrenAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getChildrenAsync(string in0, long in1, object userState) {
            if ((this.getChildrenOperationCompleted == null)) {
                this.getChildrenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetChildrenOperationCompleted);
            }
            this.InvokeAsync("getChildren", new object[] {
                        in0,
                        in1}, this.getChildrenOperationCompleted, userState);
        }
        
        private void OngetChildrenOperationCompleted(object arg) {
            if ((this.getChildrenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getChildrenCompleted(this, new getChildrenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("loginReturn")]
        public string login(string in0, string in1) {
            object[] results = this.Invoke("login", new object[] {
                        in0,
                        in1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string in0, string in1) {
            this.loginAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void loginAsync(string in0, string in1, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        in0,
                        in1}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPageReturn")]
        public RemotePage getPage(string in0, string in1, string in2) {
            object[] results = this.Invoke("getPage", new object[] {
                        in0,
                        in1,
                        in2});
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        public void getPageAsync(string in0, string in1, string in2) {
            this.getPageAsync(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void getPageAsync(string in0, string in1, string in2, object userState) {
            if ((this.getPageOperationCompleted == null)) {
                this.getPageOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPageOperationCompleted);
            }
            this.InvokeAsync("getPage", new object[] {
                        in0,
                        in1,
                        in2}, this.getPageOperationCompleted, userState);
        }
        
        private void OngetPageOperationCompleted(object arg) {
            if ((this.getPageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPageCompleted(this, new getPageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="getPage1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPageReturn")]
        public RemotePage getPage(string in0, long in1) {
            object[] results = this.Invoke("getPage1", new object[] {
                        in0,
                        in1});
            return ((RemotePage)(results[0]));
        }
        
        /// <remarks/>
        public void getPage1Async(string in0, long in1) {
            this.getPage1Async(in0, in1, null);
        }
        
        /// <remarks/>
        public void getPage1Async(string in0, long in1, object userState) {
            if ((this.getPage1OperationCompleted == null)) {
                this.getPage1OperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPage1OperationCompleted);
            }
            this.InvokeAsync("getPage1", new object[] {
                        in0,
                        in1}, this.getPage1OperationCompleted, userState);
        }
        
        private void OngetPage1OperationCompleted(object arg) {
            if ((this.getPage1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPage1Completed(this, new getPage1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("logoutReturn")]
        public bool logout(string in0) {
            object[] results = this.Invoke("logout", new object[] {
                        in0});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void logoutAsync(string in0) {
            this.logoutAsync(in0, null);
        }
        
        /// <remarks/>
        public void logoutAsync(string in0, object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[] {
                        in0}, this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new logoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("addAttachmentReturn")]
        public RemoteAttachment addAttachment(string in0, long in1, RemoteAttachment in2, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] in3) {
            object[] results = this.Invoke("addAttachment", new object[] {
                        in0,
                        in1,
                        in2,
                        in3});
            return ((RemoteAttachment)(results[0]));
        }
        
        /// <remarks/>
        public void addAttachmentAsync(string in0, long in1, RemoteAttachment in2, byte[] in3) {
            this.addAttachmentAsync(in0, in1, in2, in3, null);
        }
        
        /// <remarks/>
        public void addAttachmentAsync(string in0, long in1, RemoteAttachment in2, byte[] in3, object userState) {
            if ((this.addAttachmentOperationCompleted == null)) {
                this.addAttachmentOperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAttachmentOperationCompleted);
            }
            this.InvokeAsync("addAttachment", new object[] {
                        in0,
                        in1,
                        in2,
                        in3}, this.addAttachmentOperationCompleted, userState);
        }
        
        private void OnaddAttachmentOperationCompleted(object arg) {
            if ((this.addAttachmentCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAttachmentCompleted(this, new addAttachmentCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute(MessageName="addAttachment1")]
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("addAttachmentReturn")]
        public RemoteAttachment addAttachment(string in0, RemoteAttachment in1, [System.Xml.Serialization.SoapElementAttribute(DataType="base64Binary")] byte[] in2) {
            object[] results = this.Invoke("addAttachment1", new object[] {
                        in0,
                        in1,
                        in2});
            return ((RemoteAttachment)(results[0]));
        }
        
        /// <remarks/>
        public void addAttachment1Async(string in0, RemoteAttachment in1, byte[] in2) {
            this.addAttachment1Async(in0, in1, in2, null);
        }
        
        /// <remarks/>
        public void addAttachment1Async(string in0, RemoteAttachment in1, byte[] in2, object userState) {
            if ((this.addAttachment1OperationCompleted == null)) {
                this.addAttachment1OperationCompleted = new System.Threading.SendOrPostCallback(this.OnaddAttachment1OperationCompleted);
            }
            this.InvokeAsync("addAttachment1", new object[] {
                        in0,
                        in1,
                        in2}, this.addAttachment1OperationCompleted, userState);
        }
        
        private void OnaddAttachment1OperationCompleted(object arg) {
            if ((this.addAttachment1Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.addAttachment1Completed(this, new addAttachment1CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getSpacesReturn")]
        public RemoteSpaceSummary[] getSpaces(string in0) {
            object[] results = this.Invoke("getSpaces", new object[] {
                        in0});
            return ((RemoteSpaceSummary[])(results[0]));
        }
        
        /// <remarks/>
        public void getSpacesAsync(string in0) {
            this.getSpacesAsync(in0, null);
        }
        
        /// <remarks/>
        public void getSpacesAsync(string in0, object userState) {
            if ((this.getSpacesOperationCompleted == null)) {
                this.getSpacesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSpacesOperationCompleted);
            }
            this.InvokeAsync("getSpaces", new object[] {
                        in0}, this.getSpacesOperationCompleted, userState);
        }
        
        private void OngetSpacesOperationCompleted(object arg) {
            if ((this.getSpacesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSpacesCompleted(this, new getSpacesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("", RequestNamespace="http://soap.rpc.confluence.atlassian.com", ResponseNamespace="http://confluence/rpc/soap-axis/confluenceservice-v1")]
        [return: System.Xml.Serialization.SoapElementAttribute("getPagesReturn")]
        public RemotePageSummary[] getPages(string in0, string in1) {
            object[] results = this.Invoke("getPages", new object[] {
                        in0,
                        in1});
            return ((RemotePageSummary[])(results[0]));
        }
        
        /// <remarks/>
        public void getPagesAsync(string in0, string in1) {
            this.getPagesAsync(in0, in1, null);
        }
        
        /// <remarks/>
        public void getPagesAsync(string in0, string in1, object userState) {
            if ((this.getPagesOperationCompleted == null)) {
                this.getPagesOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPagesOperationCompleted);
            }
            this.InvokeAsync("getPages", new object[] {
                        in0,
                        in1}, this.getPagesOperationCompleted, userState);
        }
        
        private void OngetPagesOperationCompleted(object arg) {
            if ((this.getPagesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPagesCompleted(this, new getPagesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteSearchResult {
        
        private string excerptField;
        
        private long idField;
        
        private string titleField;
        
        private string typeField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string excerpt {
            get {
                return this.excerptField;
            }
            set {
                this.excerptField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(NotPermittedException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(VersionMismatchException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AlreadyExistsException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(AuthenticationFailedException))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(InvalidSessionException))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class NotPermittedException : RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class VersionMismatchException : RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class AlreadyExistsException : RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class AuthenticationFailedException : RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://rpc.confluence.atlassian.com")]
    public partial class InvalidSessionException : RemoteException {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Vector {
        
        private object[] itemField;
        
        /// <remarks/>
        public object[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemotePermission {
        
        private string lockTypeField;
        
        private string lockedByField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lockType {
            get {
                return this.lockTypeField;
            }
            set {
                this.lockTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lockedBy {
            get {
                return this.lockedByField;
            }
            set {
                this.lockedByField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteNodeStatus {
        
        private Map jVMstatsField;
        
        private Map buildStatsField;
        
        private int nodeIdField;
        
        private Map propsField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Map JVMstats {
            get {
                return this.jVMstatsField;
            }
            set {
                this.jVMstatsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Map buildStats {
            get {
                return this.buildStatsField;
            }
            set {
                this.buildStatsField = value;
            }
        }
        
        /// <remarks/>
        public int nodeId {
            get {
                return this.nodeIdField;
            }
            set {
                this.nodeIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public Map props {
            get {
                return this.propsField;
            }
            set {
                this.propsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class Map {
        
        private mapItem[] itemField;
        
        /// <remarks/>
        public mapItem[] item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://xml.apache.org/xml-soap")]
    public partial class mapItem {
        
        private object keyField;
        
        private object valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteUserInformation {
        
        private string contentField;
        
        private System.Nullable<System.DateTime> creationDateField;
        
        private string creatorNameField;
        
        private long idField;
        
        private System.Nullable<System.DateTime> lastModificationDateField;
        
        private string lastModifierNameField;
        
        private string usernameField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> creationDate {
            get {
                return this.creationDateField;
            }
            set {
                this.creationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creatorName {
            get {
                return this.creatorNameField;
            }
            set {
                this.creatorNameField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> lastModificationDate {
            get {
                return this.lastModificationDateField;
            }
            set {
                this.lastModificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string lastModifierName {
            get {
                return this.lastModifierNameField;
            }
            set {
                this.lastModifierNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        /// <remarks/>
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemotePageUpdateOptions {
        
        private bool minorEditField;
        
        private string versionCommentField;
        
        /// <remarks/>
        public bool minorEdit {
            get {
                return this.minorEditField;
            }
            set {
                this.minorEditField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string versionComment {
            get {
                return this.versionCommentField;
            }
            set {
                this.versionCommentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemotePageHistory {
        
        private long idField;
        
        private System.Nullable<System.DateTime> modifiedField;
        
        private string modifierField;
        
        private int versionField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modifier {
            get {
                return this.modifierField;
            }
            set {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteContentSummaries {
        
        private RemoteContentSummary[] contentField;
        
        private int offsetField;
        
        private int totalAvailableField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RemoteContentSummary[] content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
            }
        }
        
        /// <remarks/>
        public int totalAvailable {
            get {
                return this.totalAvailableField;
            }
            set {
                this.totalAvailableField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteContentSummary {
        
        private System.Nullable<System.DateTime> createdField;
        
        private string creatorField;
        
        private long idField;
        
        private System.Nullable<System.DateTime> modifiedField;
        
        private string modifierField;
        
        private string spaceField;
        
        private string statusField;
        
        private string titleField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modifier {
            get {
                return this.modifierField;
            }
            set {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string space {
            get {
                return this.spaceField;
            }
            set {
                this.spaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteSpaceGroup {
        
        private string creatorNameField;
        
        private string keyField;
        
        private string licenseKeyField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creatorName {
            get {
                return this.creatorNameField;
            }
            set {
                this.creatorNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string licenseKey {
            get {
                return this.licenseKeyField;
            }
            set {
                this.licenseKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteLabel {
        
        private long idField;
        
        private string nameField;
        
        private string namespaceField;
        
        private string ownerField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string @namespace {
            get {
                return this.namespaceField;
            }
            set {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string owner {
            get {
                return this.ownerField;
            }
            set {
                this.ownerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteContentPermissionSet {
        
        private RemoteContentPermission[] contentPermissionsField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public RemoteContentPermission[] contentPermissions {
            get {
                return this.contentPermissionsField;
            }
            set {
                this.contentPermissionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteContentPermission {
        
        private string groupNameField;
        
        private string typeField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string groupName {
            get {
                return this.groupNameField;
            }
            set {
                this.groupNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteAttachment {
        
        private string commentField;
        
        private string contentTypeField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private string creatorField;
        
        private string fileNameField;
        
        private long fileSizeField;
        
        private long idField;
        
        private long pageIdField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string comment {
            get {
                return this.commentField;
            }
            set {
                this.commentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contentType {
            get {
                return this.contentTypeField;
            }
            set {
                this.contentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fileName {
            get {
                return this.fileNameField;
            }
            set {
                this.fileNameField = value;
            }
        }
        
        /// <remarks/>
        public long fileSize {
            get {
                return this.fileSizeField;
            }
            set {
                this.fileSizeField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public long pageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteClusterInformation {
        
        private string descriptionField;
        
        private int memberCountField;
        
        private object[] membersField;
        
        private string multicastAddressField;
        
        private string multicastPortField;
        
        private string nameField;
        
        private bool runningField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public int memberCount {
            get {
                return this.memberCountField;
            }
            set {
                this.memberCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public object[] members {
            get {
                return this.membersField;
            }
            set {
                this.membersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string multicastAddress {
            get {
                return this.multicastAddressField;
            }
            set {
                this.multicastAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string multicastPort {
            get {
                return this.multicastPortField;
            }
            set {
                this.multicastPortField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public bool running {
            get {
                return this.runningField;
            }
            set {
                this.runningField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteUser {
        
        private string emailField;
        
        private string fullnameField;
        
        private string nameField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fullname {
            get {
                return this.fullnameField;
            }
            set {
                this.fullnameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntrySummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntry))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePageSummary))]
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public abstract partial class AbstractRemotePageSummary {
        
        private long idField;
        
        private int permissionsField;
        
        private string spaceField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public int permissions {
            get {
                return this.permissionsField;
            }
            set {
                this.permissionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string space {
            get {
                return this.spaceField;
            }
            set {
                this.spaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteBlogEntry))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteBlogEntrySummary : AbstractRemotePageSummary {
        
        private string authorField;
        
        private System.Nullable<System.DateTime> publishDateField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string author {
            get {
                return this.authorField;
            }
            set {
                this.authorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> publishDate {
            get {
                return this.publishDateField;
            }
            set {
                this.publishDateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteBlogEntry : RemoteBlogEntrySummary {
        
        private string contentField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemotePage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemotePageSummary : AbstractRemotePageSummary {
        
        private long parentIdField;
        
        /// <remarks/>
        public long parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemotePage : RemotePageSummary {
        
        private string contentField;
        
        private string contentStatusField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private string creatorField;
        
        private bool currentField;
        
        private bool homePageField;
        
        private System.Nullable<System.DateTime> modifiedField;
        
        private string modifierField;
        
        private int versionField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string contentStatus {
            get {
                return this.contentStatusField;
            }
            set {
                this.contentStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        public bool current {
            get {
                return this.currentField;
            }
            set {
                this.currentField = value;
            }
        }
        
        /// <remarks/>
        public bool homePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modifier {
            get {
                return this.modifierField;
            }
            set {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        public int version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteServerInfo {
        
        private string baseUrlField;
        
        private string buildIdField;
        
        private bool developmentBuildField;
        
        private int majorVersionField;
        
        private int minorVersionField;
        
        private int patchLevelField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string baseUrl {
            get {
                return this.baseUrlField;
            }
            set {
                this.baseUrlField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string buildId {
            get {
                return this.buildIdField;
            }
            set {
                this.buildIdField = value;
            }
        }
        
        /// <remarks/>
        public bool developmentBuild {
            get {
                return this.developmentBuildField;
            }
            set {
                this.developmentBuildField = value;
            }
        }
        
        /// <remarks/>
        public int majorVersion {
            get {
                return this.majorVersionField;
            }
            set {
                this.majorVersionField = value;
            }
        }
        
        /// <remarks/>
        public int minorVersion {
            get {
                return this.minorVersionField;
            }
            set {
                this.minorVersionField = value;
            }
        }
        
        /// <remarks/>
        public int patchLevel {
            get {
                return this.patchLevelField;
            }
            set {
                this.patchLevelField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteComment {
        
        private string contentField;
        
        private System.Nullable<System.DateTime> createdField;
        
        private string creatorField;
        
        private long idField;
        
        private System.Nullable<System.DateTime> modifiedField;
        
        private string modifierField;
        
        private long pageIdField;
        
        private long parentIdField;
        
        private string titleField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string content {
            get {
                return this.contentField;
            }
            set {
                this.contentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> created {
            get {
                return this.createdField;
            }
            set {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string creator {
            get {
                return this.creatorField;
            }
            set {
                this.creatorField = value;
            }
        }
        
        /// <remarks/>
        public long id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> modified {
            get {
                return this.modifiedField;
            }
            set {
                this.modifiedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modifier {
            get {
                return this.modifierField;
            }
            set {
                this.modifierField = value;
            }
        }
        
        /// <remarks/>
        public long pageId {
            get {
                return this.pageIdField;
            }
            set {
                this.pageIdField = value;
            }
        }
        
        /// <remarks/>
        public long parentId {
            get {
                return this.parentIdField;
            }
            set {
                this.parentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string title {
            get {
                return this.titleField;
            }
            set {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.SoapIncludeAttribute(typeof(RemoteSpace))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteSpaceSummary {
        
        private string keyField;
        
        private string nameField;
        
        private string typeField;
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string key {
            get {
                return this.keyField;
            }
            set {
                this.keyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string url {
            get {
                return this.urlField;
            }
            set {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.233")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://beans.soap.rpc.confluence.atlassian.com")]
    public partial class RemoteSpace : RemoteSpaceSummary {
        
        private string descriptionField;
        
        private long homePageField;
        
        private string spaceGroupField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        public long homePage {
            get {
                return this.homePageField;
            }
            set {
                this.homePageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string spaceGroup {
            get {
                return this.spaceGroupField;
            }
            set {
                this.spaceGroupField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void searchCompletedEventHandler(object sender, searchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class searchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal searchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteSearchResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteSearchResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void search1CompletedEventHandler(object sender, search1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class search1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal search1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteSearchResult[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteSearchResult[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSpaceCompletedEventHandler(object sender, getSpaceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSpaceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSpaceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteSpace Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteSpace)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getCommentCompletedEventHandler(object sender, getCommentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCommentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCommentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteComment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteComment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getChildrenCompletedEventHandler(object sender, getChildrenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getChildrenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getChildrenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemotePageSummary[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemotePageSummary[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPageCompletedEventHandler(object sender, getPageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemotePage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemotePage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPage1CompletedEventHandler(object sender, getPage1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPage1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPage1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemotePage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemotePage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void logoutCompletedEventHandler(object sender, logoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addAttachmentCompletedEventHandler(object sender, addAttachmentCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAttachmentCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAttachmentCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteAttachment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteAttachment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void addAttachment1CompletedEventHandler(object sender, addAttachment1CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class addAttachment1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal addAttachment1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteAttachment Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteAttachment)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getSpacesCompletedEventHandler(object sender, getSpacesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSpacesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSpacesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemoteSpaceSummary[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemoteSpaceSummary[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void getPagesCompletedEventHandler(object sender, getPagesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPagesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPagesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public RemotePageSummary[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((RemotePageSummary[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591